### PR TITLE
Optimize gas usage with some simple changes

### PR DESCRIPTION
**Pull request by behrang**
Not a drastic change, but simple changes to improve gas usage a little.

### CODE REVIEW

**Comment by KuznetsovNikita** [comment]
Little store optimisation and data parsing
Look's great!

**Comment by behrang** [comment]
Thanks

**Comment by oleganza** [comment]
@behrang thanks for participating in the contest! Since we are moving onto revision 2, i'm closing this PR.

**Comment by behrang** [comment]
No problem, it was my pleasure to join the contest.

**Pull request closed without merging**
