### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by Meena18shoth**
1.

### CODE REVIEW

**Comment by Meena18shoth** [comment]
B5690EEEBB952194

**Review by Meena18shoth — COMMENTED** [review]
****

**Comment by Meena18shoth** [comment]
Hi

**Review by didar72ahmadi — APPROVED** [review]

**Comment by Meena18shoth** [comment]
b2a09ce53069d1a27f6203129403c7a4d228d7e6

**Comment by Meena18shoth** [comment]
b2a09ce53069d1a27f6203129403c7a4d228d7e6

**Pull request closed without merging**
