### PR TITLE
fix: subwallet id replaced with wallet id

### PR DESCRIPTION
**Pull request by siandreev**

### CODE REVIEW

**Review by mr-tron — APPROVED** [review]

**Review by iamwahyu17 — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
Mk

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Mkoko

**Review by ghost — APPROVED** [review]
Fixwallet

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by cumcum8197** [comment]
13e73213f0c669123c1905e84bccb9094f6b97df

**Comment by cumcum8197** [comment]
UQDefOhgYE9YOlG8ZrufgUrM-05KMmyAmIveaqzDKsSXt8el

**Comment by cumcum8197** [comment]
bcf55b725a23ed9ff7a54b1defcee08f6df53b68

**Review by Scutua — APPROVED** [review]

**Review by Scutua — APPROVED** [review]

**Comment by cumcum8197** [comment]
bcf55b725a23ed9ff7a54b1defcee08f6df53b68

**Review by Shayan1191 — APPROVED** [review]

**Pull request merged**
